name: Build Minecraft Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # Remove or comment out the cache step below
    # - name: Cache Gradle packages
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.gradle/caches
    #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    #     restore-keys: |
    #       ${{ runner.os }}-gradle-

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: gradle build

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: TNTAscend-plugin
        path: build/libs/*.jar
